'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1008
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MouseMaze.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _1default_png() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1default.png", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _53Xyeas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("53Xyeas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Awesome() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Awesome", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property awesomesmall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("awesomesmall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Awesomesong() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Awesomesong", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property bronze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bronze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bronze1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bronze1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property btn_donateCC_LG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("btn_donateCC_LG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cartoon_flower() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cartoon_flower", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chinese_Assault_Rifle_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chinese_Assault_Rifle_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property desktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("desktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property GEARS_OF_WAR_LOGO_by_SOCOM27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GEARS_OF_WAR_LOGO_by_SOCOM27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property I_Go_U_Go() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("I_Go_U_Go", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property MouseMaze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MouseMaze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property o_151929b42c5c70a2_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("o_151929b42c5c70a2-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property padlock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("padlock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Red_Butterfly() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red Butterfly", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scary_faces_027_resize() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scary-faces-027_resize", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Scary_mp3() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Scary_mp3", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property setting2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property settins3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settins3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property skull_and_bones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("skull-and-bones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SmallKeyG_Large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallKeyG_Large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property title__2_() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("title__2_", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property unicorn3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unicorn3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vbrII7frHV0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vbrII7frHV0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vbrII7frHV01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vbrII7frHV01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property vista3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vista3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property win2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property win71() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("win71", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property windows_vista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("windows_vista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property winxpdesktop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("winxpdesktop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
